# --------------------------------------------
# This is a basic workflow to help you get started with Actions
# --------------------------------------------
name: Build

on:
  # --------------------------------------------
  # Controls when the automatic build job will be run.
  # By default uses the default branch. Runs at 03:00 UTC.
  # --------------------------------------------
  schedule:
    - cron: '0 3 * * *'
      
  # --------------------------------------------
  # Run this workflow every time a new commit pushed to the repository
  # --------------------------------------------
  push:
  
  # --------------------------------------------
  # Run this workflow every time a pull request is created or commited to it
  # --------------------------------------------
  pull_request:
    branches:
      - '**'

env:
  # -------------------------------------------------------------
  # Setting up locale to have correct keyboard mapping for swtbot
  # -------------------------------------------------------------
  LANG: "en_US.UTF-8"
# --------------------------------------------
# Defines the list of jobs
# --------------------------------------------
jobs:

  # -----------------------------------------------------
  # Build, Assemble and Deploy Job
  # -----------------------------------------------------
  build:
    name: Build, Assemble and Deploy
    runs-on: ubuntu-18.04
    
    steps:
      # --------------------------------------------
      # Checks out a copy of your repository
      # --------------------------------------------
      - name: Setup - Checkout code
        uses: actions/checkout@v2

      # --------------------------------------------
      # Setup caching for m2 repository
      # --------------------------------------------
      - name: Setup - Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-local-maven-deploy-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-local-maven-deploy-
            ${{ runner.os }}-local-maven-

      # --------------------------------------------
      # Perform various setup operations
      # --------------------------------------------
      - name: Setup - Prepare OS
        uses: virtualsatellite/ci-actions/ci-setup-action@v2
        with:
          xvfb: -x
     
      # --------------------------------------------
      # Development and Feature branches
      # --------------------------------------------
      - name: Build - Build and Deploy Decision
        id: build_decision
        uses: virtualsatellite/ci-actions/ci-build-decision-action@v2

      # --------------------------------------------
      # Development and Feature branches
      # --------------------------------------------
      - name: Build - Maven 
        run: |
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
          metacity --sm-disable --replace 2> metacity.err &
          mvn clean install -P ${{ steps.build_decision.outputs.build_type }},deployUnsecured
        if: ${{ steps.build_decision.outputs.build_type != 'release' }}
      
      # --------------------------------------------
      # Development and Feature branches
      # --------------------------------------------
      - name: Build - Maven Release
        run: |
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
          metacity --sm-disable --replace 2> metacity.err &
          mvn clean install -P ${{ steps.build_decision.outputs.build_type }},deployBackuped
        if: ${{ steps.build_decision.outputs.build_type == 'release' }}
          
      # --------------------------------------------
      # Upload Surefire Reports to github artifacts
      # --------------------------------------------            
      - name: Upload Surefire Reports on Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Surefire Reports
          path: 
            ./**/target/surefire-reports/*
     
      # ---------------------------------------------
      # Deploying to github releases
      # --------------------------------------------
      - name: Build - Deploy GH
        uses: virtualsatellite/ci-actions/ci-deploy-gh-product-action@v2
        with:
          build_profile: ${{ steps.build_decision.outputs.build_type }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.build_decision.outputs.deploy_type == 'deploy' }}
        
      # ----------------------------------------------
      # SF Deploy still to be done
      # ----------------------------------------------
      - name: Build - Deploy SF
        uses: virtualsatellite/ci-actions/ci-deploy-sf-product-action@v2
        with:
          build_profile: ${{ steps.build_decision.outputs.build_type }}
          openssl_pass: ${{ secrets.SF_SSH_KEY_OPENSSL_PASS }}
          ssh_key_pass: ${{ secrets.SF_SSH_KEY_PASS }}
          local_dir: DLRMavenTychoDemo
          remote_dir: maven-tycho-demo
        if: ${{ steps.build_decision.outputs.deploy_type == 'deploy' }}
      